### PR TITLE
Implement cert and key options

### PR DESCRIPTION
**Pull request by iguberman**
Added `cert` and `key` options (also fixed `integity_test_SUITE` and added two tests to cover these new options.  ( Still on TODO list to add equivalent tests with `cert` and `key` for every test that has `certfile` in the options).

### CODE REVIEW

**Comment by drbild** [comment]
@iguberman Could you submit a cleaned up version of this patch to upstream? 

Last commits were just 7 months ago, so I think it's worth a shot.   The changes will likely get better review from upstream than we can give and maintaining forks is a pain (particularly tracking bug fixes).  I know that in this case our fork has other changes too, but this series could be accepted upstream and our fork rebased on the new upstream.

By cleaned up I mean:

- Xaptum-specific changes removed.
- Troubleshooting commits removed via `git rebase -i` or similar.
- Common commits squashed, e.g., all the "use SSL_CTX_use_certificate_ASN1 ..." commits should be just one (again via `git rebase -i` or similar).
- More specific commit messages than "refactor CT" or "Fix CT".
- Remove the lager dependency (since adding logging is an orthogonal change that is likely to get push back).

**Comment by iguberman** [comment]
My commits went into xaptum-eng/master already squashed (they still show up here, but if I create PR to upstream master -- it will show as just one commit).    The reason why I'm holding off on creating PR to mainstream however is because I need to create a bunch of new tests: for every existing test that has certfile I need equivalent one with cert and key (I only have one test working that's good enough for our purpose `erltls:connect`).     Please let me know what are xaptum-specific changes to be removed?  @venkat-xaptum @drbild

**Comment by iguberman** [comment]
Ah, never mind, xaptum-specific is in deps script, yes that will be removed if I create upstream PR.

**Comment by drbild** [comment]
Awesome!  I didn't realize Github was squashing on merge.

**Comment by iguberman** [comment]
Not sure since when but they have three drop-down choices for merging one of which is "Squash and Merge".

**Pull request merged**
